language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
# TODO: support pytest
script:
  - python examples/example.py