{% set name = "selective_search" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/ChenjieXu/selective_search
  git_rev: v{{ version }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - joblib
    - numpy
    - python >=3.6
    - scikit-image
    - scipy

test:
  imports:
    - selective_search
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ChenjieXu/selective_search
  summary: Selective Search in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ChenjieXu
